name: Build & publish module to registry

on:
  release:
    types: [published]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: viamrobotics/build-action@v1
      with:
        version: ${{ github.ref_name }}
        ref: ${{ github.sha }}
        key-id: ${{ secrets.VIAM_DEV_API_KEY_ID }}
        key-value: ${{ secrets.VIAM_DEV_API_KEY }}
